#%RAML 1.0
title: Groceries delivery app - Shop module
version: v1
baseUri: https://shop.mini-delivery.com/
traits:
  paginated:
      queryParameters:
        page:
          description: page
          required: false
          type: integer
          format: int32
        pageSize:
          description: pageSize
          required: false
          type: integer
          format: int32    
      responses:
        200:
          headers:
            x-total-pages:  
securitySchemes:
    oauth_2_0:
        description: |
            OAuth 2.0 for authenticating API requests.
        type: OAuth 2.0
        describedBy:
            headers:
                Authorization:
                    description: |
                        Used to send a valid OAuth 2 access token. Do not use 
                        with the "access_token" query string parameter.
                    type: string
            queryParameters:
                access_token:
                    description: |
                        Used to send a valid OAuth 2 access token. Do not use together with 
                        the "Authorization" header
                    type: string
            responses:
                401:
                    description: |
                        Bad or expired token. This can happen if the user or Identity Provider
                        revoked or expired an access token. To fix, you should re-
                        authenticate the user.
                403:
                    description: |
                        Bad OAuth request (wrong consumer key, bad nonce, expired
                        timestamp...). Re-authenticating the user won't help here.
        settings:
            authorizationUri: https://example-identity-provider.com/oauth2/authorize
            accessTokenUri: https://example-identity-provider.com/oauth2/token
            authorizationGrants: [ authorization_code ]
types:
    UUID:
        type: string
        description: UUID
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
    OrderItem:
        description: element of an order
        type: object
        properties:
            orderItemId: UUID
            grossPrice:
                type: number
                description: the final sales price per unit of an item
            currency:
                type: string
                pattern: ^[A-Z]{3}$
            productName: string
            quantity: number
        example:
            orderItemId: ca543631-3df7-4d06-8091-179df67c8460
            grossPrice: 12
            currency: PLN
            productName: bread
            quantity: 3
    OrderStatus:
        type: string
        enum: [Pending, InPreparation, ReadyForDelivery, PickedUpByCourier, RejectedByShop, RejectedByCustomer, Delivered]
    Order:
        description: Groceries products order
        type: object
        properties:
            orderId: UUID
            orderItems: OrderItem[]
            creationDate: datetime
            deliveryDate: datetime
            clientAddress: 
                type: object
                properties:
                    street: string
                    city: string
                    zipCode: string
            additionalInfo: string
            orderStatus: OrderStatus
            confirmedPayment: boolean
        example:
            orderId: c2cf4e9e-0393-4189-af47-0aab382ce330
            orderItems: [
            {
                orderItemId: ca543631-3df7-4d06-8091-179df67c8460,
                grossPrice: 12,
                currency: PLN,
                productName: bread,
                quantity: 3
            }]
            creationDate: 2021-12-01T12:30:22.52Z
            deliveryDate: 2021-12-01T13:30:22.52Z
            clientAddress: 
                street: Prosta 12
                city: Warszawa
                zipCode: 00-631
            additionalInfo: Info from the client
            orderStatus: Pending
            confirmedPayment: false
    ComplaintStatus:
        type: string
        enum: [Pending, Accepted, Rejected]
    Complaint:
        description: Complaint
        type: object
        properties:
            complaintId: UUID
            orderId: UUID
            status: ComplaintStatus
            text: string
        example:
            complaintId: 061ac70b-e370-40ca-a12e-9ea146ae9429
            orderId: e41d4a1b-e771-4eae-84c8-c598ee60d627
            status: Rejected
            text: Delivery was 5 minutes late
        
/orders:
    /place:
        /{userId}:
            post:
                securedBy: [ oauth_2_0 ]
                description: Add clients order to database
                body:
                    application/json:
                        type: Order      
                responses:
                    201:
                        body:
                            application/json:
                                description: |
                                    Successfully created order
                                type: Order
                    404:
                        body:
                            text/plain:
                                description: |
                                    Failed to create order
                                type: string         
    /pending:
        /{shopId}:
            get: 
                securedBy: [ oauth_2_0 ]
                description: Get pending orders assigned to shop
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    Successfully got pending orders
                                type: Order[]
                    404:
                        body:
                            text/plain:
                                description: |
                                    Failed to get pending orders
                                type: string
    /{orderId}:
        get:
            securedBy: [ oauth_2_0 ]
            description: Get chosen order
            responses:
                200:
                    body:
                        application/json:
                            description: |
                                Successfully got chosen order
                            type: Order
                404:
                    body:
                        text/plain:
                            description: |
                                Failed to get this order
                            type: string
        /takeForPreparation:
            put:
                securedBy: [ oauth_2_0 ]
                description: Set order state to inPreparation 
                body:
                    application/json:
                        type: OrderStatus
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    Successfully taken for preperation.
                                type: OrderStatus
                    404:
                        body:
                            text/plain:
                                description: |
                                    Failed to take for preperation.
                                type: string
        /confirm:
            put:
                securedBy: [ oauth_2_0 ]
                description: Set order state to ReadyForDelivery 
                body:
                    application/json:
                        type: OrderStatus
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    Successfully taken for delivery.
                                type: OrderStatus
                    404:
                        body:
                            text/plain:
                                description: |
                                    Failed to take for delivery.
                                type: string
        /reject:
            put:
                securedBy: [ oauth_2_0 ]
                description: The order was rejected by the shop.
                body:
                    application/json:
                        type: OrderStatus
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    The order was rejected by shop.
                                type: OrderStatus
                    404:
                        body:
                            text/plain:
                                description: |
                                    Order not found
                                type: string
/complaints:
    /create:
        /{userId}:
            post:
                securedBy: [ oauth_2_0 ]
                description: Add clients complaint to database
                body:
                    application/json:
                        type: Complaint      
                responses:
                    201:
                        body:
                            application/json:
                                description: |
                                    Successfully made a complaint
                                type: Complaint
                    404:
                        body:
                            text/plain:
                                description: |
                                    Failed to make a complaint
                                type: string    
    /pending:
        /{shopId}:
            get:
                securedBy: [ oauth_2_0 ]
                description: Get pending complaints adressed to the shop
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    Successfully got pending complaints.
                                type: Complaint[]
                    404:
                        body:
                            text/plain:
                                description: |
                                    Failed to get pending complaints.
                                type: string
    /{complaintId}:
        get:
            securedBy: [ oauth_2_0 ]
            description: Get chosen complaint.
            responses:
                200:
                    body:
                        application/json:
                            description: |
                                Successfully got chosen complaint.
                            type: Complaint
                404:
                    body:
                        text/plain:
                            description: |
                                Failed to get this complaint.
                            type: string
        /accept:
            put:
                securedBy: [ oauth_2_0 ]
                description: Accept complaint 
                body:
                    application/json:
                        type: ComplaintStatus
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    Accepted complaint.
                                type: ComplaintStatus

                    404:
                        body:
                            text/plain:
                                description: |
                                    Complaint not found.
                                type: string
        /reject:
            put:
                securedBy: [ oauth_2_0 ]
                description: Reject complaint.
                body:
                    application/json:
                        type: ComplaintStatus
                responses:
                    200:
                        body:
                            application/json:
                                description: !
                                    Rejected complaint.
                                type: ComplaintStatus
                    404:
                        body:
                            text/plain:
                                description: |
                                    Complaint not found.
                                type: string
/products:
    /{productId}:
        get:
            description: Get product information
            responses:
                200:
                    body:
                        application/json:
                            description: |
                                Successfully got product info.
                            type: Product
                404:
                    body:
                        text/plain:
                            description: |
                                Product not found.
        delete:
            securedBy: [ oauth_2_0 ]
            description: remove product from shops's offer
            responses:
                200:
                    body:
                        application/json:
                            description: |
                                Succesfully deleted product.
                404:
                    body:
                        text/plain:
                            description: |
                                Product not found.
    /category:
        /{category}:
            get:
                is: [ paginated ]
                description: Get all products in the specifies category (paginated)
                responses:
                    200:
                        body:
                            application/json:
                                description: |
                                    Successfully got products info.
                                type: Product[]
                    404:
                        body:
                            text/plain:
                                description: |
                                    Category not found.
    get:
        is: [ paginated ]
        description: Get all products (paginated)
        responses:
            200:
                body:
                    application/json:
                        description: |
                            Successfully got products info.
                        type: Product[]
    post:
        securedBy: [ oauth_2_0 ]
        description: Add product to shop's offer
        body:
            application/json:
                type: Product
        responses:
            200:
                body:
                    description: |
                        Succesfully added product.
                    type: boolean
            404:
                text/plain:
                    description: |
                        Failed to add product.
                    type: string