name: Compile LaTeX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
  
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
    
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "main.tex"
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: main.pdf


